<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [1]:
import pandas as pd
import psycopg2

In [2]:
DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

In [3]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [25]:
# текст запроса
query_3_1 = f'''SELECT * FROM vacancies
'''

In [ ]:
# результат запроса
# используем метод read_sql_query, чтобы получить результаты запроса сразу в виде датафрейма
df = pd.read_sql_query(query_3_1, connection)
df

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12876\1079912922.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_1, connection)

,id,name,key_skills,schedule,experience,employment,salary_from,salary_to,area_id,employer_id
0,55312386,Компьютерный Мастер,Пользователь ПК\tРабота в команде\tРемонт ноут...,Полный день,Нет опыта,Полная занятость,64000.0,NaN,1516,5724811
1,55843014,Системный администратор,Средства криптографической защиты информации\t...,Полный день,От 3 до 6 лет,Полная занятость,NaN,NaN,130,4903713
2,54525964,Lead Java Developer to Poland,Spring Framework\tSQL\tHibernate ORM\tJava\tGit,Удаленная работа,От 3 до 6 лет,Полная занятость,NaN,NaN,160,69961
3,54525965,Lead Java Developer to Poland,Spring Framework\tSQL\tHibernate ORM\tJava\tGit,Удаленная работа,От 3 до 6 лет,Полная занятость,NaN,NaN,159,69961
4,55354053,Специалист службы поддержки с техническими зна...,NaN,Удаленная работа,Нет опыта,Частичная занятость,15000.0,NaN,1955,1740
...,...,...,...,...,...,...,...,...,...,...
49192,55589514,Специалист по информационным технологиям,Электронный документооборот\t1С: Предприятие 8...,Полный день,От 3 до 6 лет,Полная занятость,NaN,NaN,66,5109332
49193,55029668,Руководитель процессного офиса,Оптимизация бизнес-процессов\tСтратегическое м...,Полный день,От 3 до 6 лет,Полная занятость,NaN,NaN,26,51333
49194,66172263,Начальник сервисной службы,Организаторские навыки\tУправление персоналом\...,Полный день,От 1 года до 3 лет,Полная занятость,60000.0,NaN,1930,4094700
49195,66180086,Senior IOS разработчик,Swift\tRealm\tiOS\tАнглийский язык\tMVP\tMVVM\...,Полный день,От 1 года до 3 лет,Полная занятость,146456.0,244094.0,160,4469939
49196,55547842,DataOps Engineer,NaN,Удаленная работа,От 3 до 6 лет,Полная занятость,NaN,NaN,160,4978627

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [27]:
# текст запроса

query_3_2 = f'''SELECT * FROM employers
'''

In [28]:
# результат запроса
df_1 = pd.read_sql_query(query_3_2, connection)
df_1

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12876\2117514097.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_1 = pd.read_sql_query(query_3_2, connection)

            id                                               name  area
0         2393                   Программный Продукт, ИТ-компания     1
1        72977                                          БАРС Груп    88
2         3155  Бест, Торгово-производственная компания, Екате...     3
3          675                                   КОРУС Консалтинг     2
4      1840010  филиал ФКУ Налог-Сервис ФНС России в Республик...    88
...        ...                                                ...   ...
23496  1441774                                              МарКо    88
23497  4718575                                      MKomov Studio    73
23498  3702770                                  АКИБ Ипотека-банк  2759
23499  5636092                                        ГИМ-КЛИНИКА    99
23500  2064382                                             Рыббла   104

[23501 rows x 3 columns]

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [16]:
# текст запроса
query_3_3 = f'''SELECT * FROM areas
'''

In [17]:
# результат запроса
df_2 = pd.read_sql_query(query_3_3, connection)
df_2

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\4210146866.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_2 = pd.read_sql_query(query_3_3, connection)

        id              name
0     2758           Тбилиси
1        8            Майкоп
2     1180          Нерюнгри
3     1240       Новокузнецк
4        2   Санкт-Петербург
...    ...               ...
1357  5043  Звёздный Городок
1358  3934       Воротынск\n
1359  4825             Чемал
1360  3708         Усть-Нера
1361  2432         Каневская

[1362 rows x 2 columns]

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [18]:
# текст запроса
query_3_4 = f'''SELECT * FROM industries
'''

In [19]:
# результат запроса
df_3 = pd.read_sql_query(query_3_4, connection)
df_3

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\197951593.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_3 = pd.read_sql_query(query_3_4, connection)

          id                                               name
0      7.540                Разработка программного обеспечения
1      7.539  Системная интеграция,  автоматизации технологи...
2     27.550              Безалкогольные напитки (производство)
3     27.551  Безалкогольные напитки (продвижение, оптовая т...
4     13.664             Управление и эксплуатация недвижимости
..       ...                                                ...
289   37.626             Ассоциация в сфере культуры, искусства
290   42.603                              Табак  (производство)
291   29.532                           Рыболовство, рыбоводство
292   37.627                      Благотворительная организация
293  388.505  Оборудование для деревообработки, заготовки ле...

[294 rows x 2 columns]

***

In [ ]:
# выводы по предварительному анализу данных
База данных содержит: 49197 вакансий, от 23501 работадателей, в 1362 населенных пунктах, по 294 направленмям дейтельности.

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [92]:
# текст запрос
query_4_1 = f'''SELECT areas.name, vacancies.name
FROM areas
INNER JOIN vacancies
ON areas.id = vacancies.area_id
'''

In [98]:
# результат запроса
df_4_1 = pd.read_sql_query(query_4_1, connection)
df_4_1.columns=['area','name']
df_4_1['area'].value_counts()

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\578778627.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_1 = pd.read_sql_query(query_4_1, connection)

area
Москва                            5333
Санкт-Петербург                   2851
Минск                             2112
Новосибирск                       2006
Алматы                            1892
                                  ...
Тура (Красноярский край)             1
Новоульяновск                        1
Абхазия                              1
Заполярный (Ямало-Ненецкий АО)       1
Изобильный                           1
Name: count, Length: 769, dtype: int64

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [138]:
# текст запроса
query_4_2= f'''SELECT 
    COUNT(*) AS cnt
FROM 
    vacancies
WHERE 
    salary_from IS NOT NULL 
    OR salary_to IS NOT NULL
'''

In [139]:
# результат запроса
df_4_2 = pd.read_sql_query(query_4_2, connection)
df_4_2

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\2677234658.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_2 = pd.read_sql_query(query_4_2, connection)

     cnt
0  24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [140]:
# текст запроса
query_4_3= f'''SELECT 
    ROUND(AVG(salary_from)) AS avg_salary_from,  -- средняя нижняя граница зарплаты
    ROUND(AVG(salary_to)) AS avg_salary_to       -- средняя верхняя граница зарплаты
FROM 
    vacancies
WHERE 
    salary_from IS NOT NULL 
    OR salary_to IS NOT NULL
'''

In [142]:
# результат запроса
df_4_3 = pd.read_sql_query(query_4_3, connection)
df_4_3

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\3595259731.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_3 = pd.read_sql_query(query_4_3, connection)

   avg_salary_from  avg_salary_to
0          71065.0       110537.0

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [143]:
# текст запроса
query_4_4= f'''SELECT 
    schedule,
    employment,
    COUNT(*) AS cnt
FROM 
    vacancies
GROUP BY 
    schedule, employment
ORDER BY 
    cnt DESC
LIMIT 2
'''

In [144]:
# результат запроса
df_4_4 = pd.read_sql_query(query_4_4, connection)
df_4_4

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\2028972612.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_4 = pd.read_sql_query(query_4_4, connection)

           schedule        employment    cnt
0       Полный день  Полная занятость  35367
1  Удаленная работа  Полная занятость   7802

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [145]:
# текст запроса
query_4_5= f'''SELECT 
    experience AS "Требуемый опыт работы",
    COUNT(*) AS cnt
FROM 
    vacancies
GROUP BY 
    experience
ORDER BY 
    cnt ASC
'''

In [146]:
# результат запроса
df_4_5 = pd.read_sql_query(query_4_5, connection)
df_4_5

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\210463167.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_5 = pd.read_sql_query(query_4_5, connection)

  Требуемый опыт работы    cnt
0           Более 6 лет   1337
1             Нет опыта   7197
2         От 3 до 6 лет  14511
3    От 1 года до 3 лет  26152

***

In [ ]:
# выводы по детальному анализу вакансий
Размер города влияет на количество вакансий, чем город больше тем больше вакансий предлогается.
Примерно в половине вакансий не заполнены сведения о ЗП. В среднем ЗП находится в пределах от 71065 до	110537.
При полной занятости очно необходимо работать в 35367, а удаленно 7802 вакансиях.
В половине случаев работадатели рассматривают работников с опытом работы от 1 года до 3 лет (26152). Далее идут вакансии с опытом работы от 3 до 6 лет (14511).
Опыт не требуется в 7197 вакансий. Специалисты с опытом работы более 6 лет, требуются  в 1337 вакансиях.
Основное кол-во вакансий предлагается специалистам с опытом работы от 1 года до 6 лет.

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [29]:
# текст запроса
query_5_1= f'''SELECT 
    e.name AS employer_name,
    COUNT(v.id) AS vacancy_count
FROM 
    employers e
LEFT JOIN 
    vacancies v ON e.id = v.employer_id
GROUP BY 
    e.name
ORDER BY 
    vacancy_count DESC
'''

In [30]:
# результат запроса
df_5_1 = pd.read_sql_query(query_5_1, connection)
df_5_1

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12876\1147638897.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_1 = pd.read_sql_query(query_5_1, connection)

                            employer_name  vacancy_count
0                                  Яндекс           1933
1                              Ростелеком            491
2                                Тинькофф            444
3                                    СБЕР            428
4                           Газпром нефть            331
...                                   ...            ...
23170      Капитал Лайф Страхование Жизни              0
23171                            AGASTONE              0
23172                       Независимость              0
23173  Верховный Суд Республики Татарстан              0
23174                            Трекмарк              0

[23175 rows x 2 columns]

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [179]:
# текст запроса
query_5_2= f'''WITH regions_with_employers AS (
    SELECT 
        a.name AS region,
        COUNT(DISTINCT e.id) AS employer_count
    FROM 
        areas a
    LEFT JOIN 
        employers e ON a.id = e.area
    LEFT JOIN 
        vacancies v ON a.id = v.area_id
    WHERE 
        v.id IS NULL  -- выбираем регионы без вакансий
    GROUP BY 
        a.name
)
SELECT 
    region,
    employer_count
FROM 
    regions_with_employers
ORDER BY 
    employer_count DESC
LIMIT 1
'''

In [180]:
# результат запроса
df_5_2 = pd.read_sql_query(query_5_2, connection)
df_5_2

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\2306256317.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_2 = pd.read_sql_query(query_5_2, connection)

   region  employer_count
0  Россия             410

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [ ]:
# текст запроса
query_5_3= f'''SELECT 
    e.name AS employer_name,
    COUNT(DISTINCT v.area_id) AS region_count
FROM 
    employers e
LEFT JOIN 
    vacancies v ON e.id = v.employer_id
GROUP BY 
    e.name
ORDER BY 
    region_count DESC
'''

In [198]:
# результат запроса
df_5_3 = pd.read_sql_query(query_5_3, connection)
df_5_3

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\133400711.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_3 = pd.read_sql_query(query_5_3, connection)

                employer_name  region_count
0                      Яндекс           181
1                  Ростелеком           152
2                  Спецремонт           116
3      Поляков Денис Иванович            88
4                   ООО ЕФИН             71
...                       ...           ...
23170                  СДЕЛКА             0
23171            Alandr Group             0
23172                     СДК             0
23173      Lemon Land Lombard             0
23174                  Махина             0

[23175 rows x 2 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [199]:
# текст запроса
query_5_4= f'''SELECT 
    COUNT(*) AS employers_without_industry
FROM 
    employers e
LEFT JOIN 
    employers_industries ei ON e.id = ei.employer_id
LEFT JOIN 
    industries i ON ei.industry_id = i.id
WHERE 
    i.id IS NULL
'''

In [200]:
# результат запроса
df_5_4 = pd.read_sql_query(query_5_4, connection)
df_5_4

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\1045119256.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_4 = pd.read_sql_query(query_5_4, connection)

   employers_without_industry
0                        8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [31]:
# текст запроса

query_5_5= f'''SELECT 
    e.name AS company_name
FROM 
    employers e
JOIN 
    employers_industries ei ON e.id = ei.employer_id
JOIN 
    industries i ON ei.industry_id = i.id
GROUP BY 
    e.name
HAVING 
    COUNT(DISTINCT i.id) = 4
'''

In [32]:
# результат запроса
df_5_5 = pd.read_sql_query(query_5_5, connection)
df_5_5.loc[2]

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12876\342998231.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_5 = pd.read_sql_query(query_5_5, connection)

company_name    2ГИС
Name: 2, dtype: str

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [34]:
# текст запроса
query_5_6= f'''SELECT 
    COUNT(*) AS employer_count
FROM 
    employers e
JOIN 
    employers_industries ei ON e.id = ei.employer_id
JOIN 
    industries i ON ei.industry_id = i.id
WHERE 
    i.name = 'Разработка программного обеспечения'
'''

In [35]:
# результат запроса
df_5_6 = pd.read_sql_query(query_5_6, connection)
df_5_6

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12876\2713946032.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_6 = pd.read_sql_query(query_5_6, connection)

   employer_count
0            3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [52]:
# код для получения списка городов-милионников

import requests
from bs4 import BeautifulSoup
import re

subject = 'Города-миллионеры_России'
url = 'https://ru.wikipedia.org/w/api.php'

params = {
    'action': 'parse',           # Используем действие "parse"
    'format': 'json',
    'page': subject,
    'prop': 'text',             # Получаем HTML-текст страницы
}
#Любой header, без него запрос не принимается
headers = {
    'User-Agent': 'MyPythonScript/1.0 (your_email@example.com)'
}

response = requests.get(url, params=params, headers=headers)
response.encoding = 'utf-8'

data = response.json()
#К сожалению, таблица формируется JS и не передается в json, поэтому используем страницу в виде html
# Извлекаем HTML-код из ответа
html_content = data['parse']['text']['*']

# Создаем объект BeautifulSoup для парсинга HTML
soup = BeautifulSoup(html_content, 'html.parser')
#Найдем таблицу
target_table = soup.find('tbody')
#С помощью regexp получим все заголовки ссылок
cities = re.findall(r'title=("[\w -]+")', str(target_table))
#Уберем лишние ковычки
cities = [city.strip('"') for city in cities]
print(cities)

['Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Казань', 'Красноярск', 'Нижний Новгород', 'Челябинск', 'Уфа', 'Краснодар', 'Самара', 'Ростов-на-Дону', 'Омск', 'Воронеж', 'Пермь', 'Волгоград']

In [ ]:
# текст запроса

query_5_7 = '''
WITH yandex_vacancies AS (
    SELECT 
        areas.id
,areas.name
 AS area_name
    FROM
        vacancies 
    JOIN 
        employers ON vacancies.employer_id=employers.id
    JOIN 
        areas ON vacancies.area_id=areas.id
    WHERE 
        employers.name='Яндекс' 
        AND areas.name
 IN %s
    )
SELECT 
    area_name, COUNT(id) AS cnt 
FROM 
    yandex_vacancies
GROUP BY 
    area_name
UNION ALL
SELECT 
    'total' AS area_name, 
    COUNT(id) AS cnt
FROM 
    yandex_vacancies;
'''

In [59]:
# результат запроса
df_5_7 = pd.read_sql_query(query_5_7, connection,params=(tuple(cities),))
df_5_7.rename(columns={'area_name': 'Регион/Город','cnt': 'Количество вакансий компании'},inplace=True)
df_5_7

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12876\1596127438.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_7 = pd.read_sql_query(query_5_7, connection,params=(tuple(cities),))

       Регион/Город  Количество вакансий компании
0            Казань                            25
1   Нижний Новгород                            36
2      Екатеринбург                            39
3       Новосибирск                            35
4        Красноярск                            23
5              Омск                            21
6           Воронеж                            32
7             Пермь                            25
8               Уфа                            26
9         Челябинск                            22
10           Москва                            54
11  Санкт-Петербург                            42
12        Волгоград                            24
13           Самара                            26
14   Ростов-на-Дону                            25
15        Краснодар                            30
16            total                           485

***

In [ ]:
# выводы по анализу работодателей
Наибольшее кол-во вакансий представлено от крупных компаний IT и финансовой сферы. Яндек и Ростелеком ищат сотрудников в наибольшем кол-ве регионов.
У 8419 работадателей не указана сфера деятельности. Разработкой ПО занимаются 3553 работадателя.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [232]:
# текст запроса
query_6_1= f'''SELECT 
    COUNT(*) AS data_vacancies_count
FROM 
    vacancies
WHERE 
    LOWER(name) LIKE '%data%' 
    OR LOWER(name) LIKE '%данн%'
'''

In [233]:
# результат запроса
df_6_1 = pd.read_sql_query(query_6_1, connection)
df_6_1

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\1281472032.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_1 = pd.read_sql_query(query_6_1, connection)

   data_vacancies_count
0                  1771

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [ ]:
# текст запроса
query_6_2= f'''SELECT 
    COUNT(*) AS junior_ds_vacancies
FROM 
    vacancies
WHERE 
    -- Проверяем, относится ли вакансия к Data Science
    (LOWER(name) LIKE '%data scientist%'
     OR LOWER(name) LIKE '%data science%'
     OR LOWER(name) LIKE '%исследователь данных%'
     OR (LOWER(name) LIKE '%ml%' AND LOWER(name) NOT LIKE '%html%')
     OR LOWER(name) LIKE '%machine learning%'
     OR LOWER(name) LIKE '%машинн%обучен%')
    
    -- Проверяем уровень вакансии
    AND (
        LOWER(name) LIKE '%junior%'
        OR experience = 'Нет опыта'
        OR employment = 'Стажировка'
    )
    '''

In [241]:
# результат запроса
df_6_2 = pd.read_sql_query(query_6_2, connection)
df_6_2

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\118162426.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_2 = pd.read_sql_query(query_6_2, connection)

   junior_ds_vacancies
0                   51

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [270]:
# текст запроса
query_6_3= f'''SELECT 
    COUNT(*) AS sql_vacancies_count
FROM 
    vacancies
WHERE 
    -- Проверяем, относится ли вакансия к Data Science
    (LOWER(name) LIKE '%data scientist%'
     OR LOWER(name) LIKE '%data science%'
     OR LOWER(name) LIKE '%исследователь данных%'
     OR (LOWER(name) LIKE '%ml%' AND LOWER(name) NOT LIKE '%html%')
     OR LOWER(name) LIKE '%machine learning%'
     OR LOWER(name) LIKE '%машинн%обучен%')
    
    -- Проверяем наличие навыков SQL или Postgres
    AND (key_skills LIKE '%SQL%'
        OR key_skills LIKE '%postgres%')
'''

In [271]:
# результат запроса
df_6_3 = pd.read_sql_query(query_6_3, connection)
df_6_3

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\3310962512.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_3 = pd.read_sql_query(query_6_3, connection)

   sql_vacancies_count
0                  229

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [272]:
# текст запроса
query_6_4= f'''SELECT 
    COUNT(*) AS python_vacancies_count
FROM 
    vacancies
WHERE 
    -- Проверяем, относится ли вакансия к Data Science
    (LOWER(name) LIKE '%data scientist%'
     OR LOWER(name) LIKE '%data science%'
     OR LOWER(name) LIKE '%исследователь данных%'
     OR (LOWER(name) LIKE '%ml%' AND LOWER(name) NOT LIKE '%html%')
     OR LOWER(name) LIKE '%machine learning%'
     OR LOWER(name) LIKE '%машинн%обучен%')
    
    -- Проверяем наличие навыков Python
    AND (key_skills LIKE '%Python%')
'''

In [273]:
# результат запроса
df_6_4 = pd.read_sql_query(query_6_4, connection)
df_6_4

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\614304167.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_4 = pd.read_sql_query(query_6_4, connection)

   python_vacancies_count
0                     357

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [410]:
# текст запроса
query_6_5= f'''SELECT 
    ROUND(
        AVG(
            LENGTH(key_skills) - 
            LENGTH(REPLACE(key_skills, CHR(9), '')) + 1
        ), 
        2
    ) AS avg_skills_count
FROM 
    vacancies
WHERE 
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR (name LIKE '%ML%' AND LOWER(name) NOT LIKE '%html%')
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
    AND key_skills IS NOT NULL
    AND key_skills <> ''
'''

In [411]:
# результат запроса
df_6_5 = pd.read_sql_query(query_6_5, connection)
df_6_5

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\4089566367.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_5 = pd.read_sql_query(query_6_5, connection)

   avg_skills_count
0              6.41

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [412]:
# текст запроса
query_6_6= f'''WITH salary_calc AS (
    SELECT
        experience,
        (COALESCE(salary_from, salary_to) + COALESCE(salary_to, salary_from)) / 2 AS calculated_salary
    FROM vacancies
    WHERE 
        -- Фильтрация по DS-вакансиям
        (LOWER(name) LIKE '%data scientist%'
         OR LOWER(name) LIKE '%data science%'
         OR LOWER(name) LIKE '%исследователь данных%'
         OR (name LIKE '%ML%' AND LOWER(name) NOT LIKE '%html%')
         OR LOWER(name) LIKE '%machine learning%'
         OR LOWER(name) LIKE '%машинн%обучен%')
        
        -- Условие на наличие хотя бы одного заполненного поля зарплаты
        AND (salary_from IS NOT NULL OR salary_to IS NOT NULL)
)
SELECT
    experience,
    ROUND(AVG(calculated_salary)) AS avg_salary
FROM salary_calc
GROUP BY experience
'''

In [413]:
# результат запроса
df_6_6 = pd.read_sql_query(query_6_6, connection)
df_6_6

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\2297777544.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_6 = pd.read_sql_query(query_6_6, connection)

           experience  avg_salary
0       От 3 до 6 лет    243115.0
1  От 1 года до 3 лет    139675.0
2           Нет опыта     74643.0

***

In [ ]:
# выводы по предметному анализу
К данным имеет отношение 1771 вакансий, из которых 51 вакансия для начинающих. С SQL и postgres связано 229 вакансий. Навыки Python потребуются в 357 вакансиях.
Соискатели, в среднем, должны обладать 6-7 навыками. С ростом опыта специалисты по данным получают более высокую ЗП.

# Общий вывод по проекту

In [ ]:
# подведем итог исследования, обобщите выводы
# здесь можно (это будет плюсом) провести дополнительные исследования данных, сделать прогнозы, продумать варианты продолжения исследования
В результате изучения БД мы пришли к следующим выводам:
    1 Большинство вакансий находится в крупных городах и предаставляется крупными компаниями.
    2 Крупные компании представлены в большем количестве регионов чем остальные.
    3 К данным имеет отношение около 3% вакансий. В основном требуются специалисты с опытом работы от 1 до 6 лет.
    4 С ростом опыта специалисты по данным получают более высокую ЗП.

Иссдедоване средней ЗП специалистов по данным в зависимости от названия должности.

In [445]:
query_7_1= f'''WITH salary_calc AS (
    SELECT
        name,
        CASE 
            WHEN salary_from IS NOT NULL AND salary_to IS NOT NULL THEN (salary_from + salary_to) / 2
            WHEN salary_from IS NOT NULL THEN salary_from
            WHEN salary_to IS NOT NULL THEN salary_to
        END AS calculated_salary
    FROM vacancies
    WHERE 
        -- Фильтрация по DS-вакансиям
        (LOWER(name) LIKE '%data scientist%'
         OR LOWER(name) LIKE '%data science%'
         OR LOWER(name) LIKE '%исследователь данных%'
         OR (LOWER(name) LIKE '%ML%' AND LOWER(name) NOT LIKE '%html%')
         OR LOWER(name) LIKE '%machine learning%'
         OR LOWER(name) LIKE '%машинн%обучен%')
        
        -- Условие на наличие хотя бы одного заполненного поля зарплаты
        AND (salary_from IS NOT NULL OR salary_to IS NOT NULL)
)
SELECT
    name,
    ROUND(AVG(calculated_salary)) AS avg_salary
FROM salary_calc
GROUP BY name
ORDER BY avg_salary DESC
'''

In [446]:
df_7_1= pd.read_sql_query(query_7_1, connection)
df_7_1

C:\Users\dmitry\AppData\Local\Temp\ipykernel_12828\967735871.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_7_1= pd.read_sql_query(query_7_1, connection)

                                                 name  avg_salary
0                        ML Engineer \ Data scientist    450000.0
1   ML & Advanced analytics Lead / Lead Data Scien...    350000.0
2   Senior Data Analyst / Senior Data Scientist (A...    300000.0
3                               Senior Data Scientist    300000.0
4               Руководитель направления Data Science    300000.0
5                                 Lead data scientist    300000.0
6                                      Data Scientist    266667.0
7                           Machine Learning Engineer    253277.0
8                              Data scientist/Analyst    250000.0
9     C++ Machine Learning Engineer (Computer Vision)    233794.0
10                   Data scientist / Product analyst    225000.0
11                              Middle Data Scientist    225000.0
12                               Data science инженер    225000.0
13                  Data Scientist (Machine Learning)    222104.0
14               Data Scientist/ML Engineer (Middle+)    205000.0
15                         Machine Learning Developer    200000.0
16                      Инженер по машинному обучению    200000.0
17               NLP Machine Learning Engineer Python    200000.0
18                       Middle/Senior Data Scientist    200000.0
19               Middle ML / Data Science разработчик    170000.0
20                                     Data scientist    162500.0
21                   Аналитик данных / Data scientist    155000.0
22                   Аналитик данных (Data Scientist)    150000.0
23        Deep Learning/Machine Learning NLP Engineer    150000.0
24  Data scientist / Исследователь-программист данных    143500.0
25                    Data Scientist/BackEnd (Python)    140000.0
26  Data Scientist / Data Analyst в области иннова...    130000.0
27                        Data Science / Data Analyst    120000.0
28                           Data Scientist/Математик    119000.0
29  Исследователь в области машинного обучения и м...    115000.0
30                        Специалист Data Science (R)    110000.0
31          Data Scientist (Computer Vision) / Middle    100000.0
32  Исследователь алгоритмов машинного обучения / ...    100000.0
33  Математик-аналитик (data scientist / data anal...     98000.0
34                  Автор работ по машинному обучению     90000.0
35  Программист Python/ Data Scientist (junior / m...     80000.0
36                            Data Scientist (Junior)     72500.0
37          Data Scientist (Computer Vision) / Junior     70000.0
38                           Data Scientist (Junior+)     60000.0
39                              Junior Data Scientist     50000.0
40                     Junior Data Scientist (Стажер)     37000.0

Вывод: ЗП зависит от предлагаемой должноси, чем выше ответственность и должность, тем выше ЗП.

In [4]:
connection.close()